FROM python:3.10

WORKDIR /app

COPY requirements.dev.txt .

RUN pip install -r requirements.dev.txt

COPY . .

EXPOSE 8000

CMD ["fastapi", "dev", "app/main.py", "--port", "8000", "--host", "0.0.0.0"]